language: bash
services: docker
sudo: required
install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --credential yes
env:
  - IMAGE=core
  - IMAGE=ffmpeg
  - IMAGE=opencv
  - IMAGE=jupyter
script:
  - cd ${IMAGE}
  - docker build -t okwrtdsh/rpi-${IMAGE}:latest .
  - docker images
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" ;
      docker push okwrtdsh/rpi-${IMAGE}:latest ;
    fi
